railbook/config/routes.rb
require 'TimeConstraint'

Railbook::Application.routes.draw do
  get "ajax/index"

  resources :fun_comments

  resources :members

  resources :reviews

  resources :authors

  resources :users

  get "view/keyword"

  resources :books

  match ':controller(/:action(/:id(.:format)))'

end

railbook/app/models/TimeConstraint.rb
class TimeConstraint
  def matches?(request)
    current = Time.now
    current.hour >= 9 && current.hour < 18
  end
end

railbook/app/models/author.rb
#coding: utf-8

class Author < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :books
  has_many :comments, :class_name => 'FunComment',
    :foreign_key => 'author_no', :conditions => { :deleted => false }

  validate :file_invalid?

  def data=(data)
    self.ctype = data.content_type
    self.photo = data.read
  end

  private 
  def file_invalid?
    ps = ['image/jpeg', 'image/gif', 'image/png']
    errors.add(:photo, 'は画像ファイルではありません。') if !ps.include?(self.ctype)
    errors.add(:photo, 'のサイズが1MBを超えています。') if self.photo.length > 1.megabyte
  end
end

railbook/app/models/authors_book.rb
class AuthorsBook < ActiveRecord::Base
  belongs_to :author
  belongs_to :book
end

railbook/app/models/book.rb
# coding: utf-8

class Book < ActiveRecord::Base
  scope :gihyo, where(:publish => '技術評論社')
  scope :newer, order('published DESC')
  scope :top10, newer.limit(10)
  scope :whats_new, lambda {
  |pub| where(:publish => pub).order('published DESC').limit(5)
}

  has_many :reviews
  has_and_belongs_to_many :authors
  has_many :users, :through => :reviews

  # validates :isbn,
  #   :presence => { :message => 'は必須です'},
  #   :uniqueness => { :allow_blank => true, :message => '%{value}は一意でなければなりません' },
  #   :length => { :is => 17 , :allow_blank => true, :message => '%{value}は%{count}桁でなければなりません' },
  #   :format => { :with => /^[0-9]{3}-[0-9]{1}-[0-9]{3,5}-[0-9]{4}-[0-9X]{1}$/, :allow_blank => true, :message => '%{value}は正しい形式ではありません' }

  validates :isbn,
    :presence => true,
    :uniqueness => true,
    # :uniqueness => { :allow_blank => true },
    :length => { :is => 17 },
    # :length => { :is => 17 , :allow_blank => true },
    :format => { :with => /^[0-9]{3}-[0-9]{1}-[0-9]{3,5}-[0-9]{4}-[0-9X]{1}$/ }
    # :format => { :with => /^[0-9]{3}-[0-9]{1}-[0-9]{3,5}-[0-9]{4}-[0-9X]{1}$/, :allow_blank => true }
    # :isbn => { :allow_old => true }

  validates :title,
    :presence => true,
    :length => { :minimum => 1, :maximum => 100 }
  validates :price,
    :numericality => { :only_integer => true, :less_than => 10000 }
  validates :publish,
    :inclusion => { :in => ['技術評論社', '翔泳社', '秀和システム', '日経BP社', 'インプレスジャパン'] }
  # validates :title, :uniqueness => { :scope => :publish }

  # validate :isbn_valid?

  # private
  # def isbn_valid?
  #   errors.add(:isbn, 'は正しい形式ではありません。') unless isbn =~ /^[0-9]{3}-[0-9]{1}-[0-9]{3,5}-[0-9]{4}-[0-9X]{1}$/
  # end

  after_destroy :history_book
  #after_destroy :history_book, :unless => Proc.new { |b| b.publish == "翔泳社" }


   private
   def history_book
    logger.info('deleted: ' + self.inspect)
   end

  # after_destroy do |b|
  #   logger.info('deleted: ' + b.inspect)
  # end

  # after_destroy BookCallbacks.new
end

railbook/app/models/book_callbacks.rb
class BookCallbacks
  cattr_accessor :logger
  self.logger ||= Rails.logger

  def after_destroy(b)
    logger.info('deleted: ' + b.inspect)
  end
end

railbook/app/models/book_observer.rb
class BookObserver < ActiveRecord::Observer
  def after_save(b)
    NoticeMailer.sendmail_book(b).deliver
  end
end

railbook/app/models/book_sweeper.rb
class BookSweeper < ActionController::Caching::Sweeper
  observe Book

  def after_create(book)
    gc_cache(book)
  end

  def after_update(book)
    gc_cache(book)
  end

  def after_destroy(book)
    gc_cache(book)
  end

  private
  def gc_cache(book)
    expire_action :controller => 'books', :action => 'index'
    expire_action :controller => 'books', :action => 'show', :id => book.id
  end
end 

railbook/app/models/fun_comment.rb
class FunComment < ActiveRecord::Base
end

railbook/app/models/member.rb
class Member < ActiveRecord::Base
end

railbook/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
  # default_scope order('updated_at DESC')
end

railbook/app/models/user.rb
class User < ActiveRecord::Base
  has_one :author
  has_many :reviews
  has_many :books, :through => :reviews

  attr_protected :roles
  # attr_accessible :username, :password, :email, :dm

  validates :agreement, :acceptance => { :accept => 'yes' }
  # validates :agreement, :acceptance => { :on => :create }
   validates :email, :confirmation => true
  # validates :email, :presence => { :unless => 'dm.blank?' }
  # validates :email, :presence => { :if => '!dm.blank?' } 

  # validates :email, :presence => { :unless => :sendmail? }

  # def sendmail?
  #   dm.blank?
  # end

  # validates :email,
  #   :presence => { :unless => Proc.new { |u| u.dm.blank? } }

  def self.authenticate(username, password)
    where(:username => username,
      :password => Digest::SHA1.hexdigest(password)).first
  end
end

railbook/app/helpers/ajax_helper.rb
module AjaxHelper
end

railbook/app/helpers/books_helper.rb
module BooksHelper
end

railbook/app/helpers/ctrl_helper.rb
module CtrlHelper
end

railbook/app/helpers/extra_helper.rb
module ExtraHelper
end

railbook/app/helpers/hello_helper.rb
module HelloHelper
end

railbook/app/helpers/login_helper.rb
module LoginHelper
end

railbook/app/helpers/record_helper.rb
module RecordHelper
end

railbook/app/helpers/users_helper.rb
module UsersHelper
end

railbook/app/helpers/view_helper.rb
module ViewHelper
end

railbook/app/views/view/capture.html.erb
<% @current = capture do %>
ただいまの時刻は<%= Time.now %>です。
<% end %>

<%= @current %>
<div style="color:Red"><%= @current %></div>

railbook/app/views/view/conc.html.erb
<table border="1">
  <tr>
    <th>ISBNコード</th><th>書名</th><th>価格</th>
    <th>出版社</th><th>刊行日</th><th>CD-ROM</th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.isbn %></td>
    <td><%= book.title %></td>
    <td><%= book.price %>円
      <% if book.price >= 3000
        concat image_tag('expensive.gif')
      end %>
    </td>
<%
=begin
%>
    <td><%= book.price %>円
      <% if book.price >= 3000 %>
      <%= image_tag 'expensive.gif' %>
    <% end %>
    </td>
<%
=end
%>
    <td><%= book.publish %></td>
    <td><%= book.published %></td>
    <td><%= book.cd %></td>
  </tr>
<% end %>
</table>

railbook/app/views/view/discovery.html.erb
<%= auto_discovery_link_tag(:rss,
  { :controller => 'books', :action => 'index', :id => 'rails' },
  { :title => 'サーバサイドの学び舎 - WINGS -'}
) %>


<%
=begin
%>
<%= auto_discovery_link_tag(:rss,
  'http://www.wings.msn.to/contents/rss.php',
  { :title => 'サーバサイドの学び舎 - WINGS -'}
) %>
<%
=end
%>

railbook/app/views/view/excerpt.html.erb
<% msg = 'RailsはRubyベースのフレームワークです。Railsに影響を受けたフレームワークには、Catalystやsymfonyなどがあります。' %>

<%= excerpt(msg, 'Catalyst', { :radius => 10 }) %><br />

<%= excerpt(msg, 'Rails', { :radius => 10 }) %><br />

<%= excerpt(msg, 'Catalyst', { :radius => 10, :omission => '～' }) %>

railbook/app/views/view/format.html.erb
<%
@name = 'WINGSプロジェクト 有限会社'
@sum  = 87512.35
@shop = 52
%>
<%= sprintf('%.10s：全店舗数%d件の月総売り上げ%.1f千円、店舗平均は%10.3f千円です。', @name, @shop, @sum, @sum / @shop) %>

railbook/app/views/view/helper2.html.erb
<% @books = Book.all %>
<%= list_tag(@books, 'title') %>

railbook/app/views/view/helper3.html.erb
<%= blockquote_tag('http://www.wings.msn.to', 'サーバサイド技術の学び舎',
  :class => 'quote') do %>
  WINGSプロジェクトは、当初、ライター山田祥寛のサポート（検証・査読・校正作業）集団という位置づけで開始されたコミュニティでしたが、2002年12月にメンバを大幅に増強し、本格的な執筆者プロジェクトとして生まれ変わりました。
  <%= image_tag('http://www.wings.msn.to/image/wings.jpg') %>
<% end %>

<%
=begin
%>
<%= blockquote_tag2('http://www.wings.msn.to', 'サーバサイド技術の学び舎',
  'WINGSプロジェクトは、本格的な執筆者プロジェクトとして生まれ変わりました。', :class => 'quote') %>
<%
=end
%>

railbook/app/views/view/link.html.erb
<%= link_to('サポートサイト', 'http://www.wings.msn.to/') %><br />

<%= link_to('トップ', { :controller => 'hello', :action => 'index' },
  { :id => 'link', :class => 'menu' }) %><br />

<%= link_to '削除', book_path(1),
  {:confirm => '削除しても良いですか？', :method => :delete } %><br />

<%= link_to('トップ', :controller => 'hello', :action => 'index',
  :id => 'link', :class => 'menu') %><br />

railbook/app/views/view/linkif.html.erb
<% #@user = User.new %>
<%= link_to_if(@user.nil?, 'ログイン',
  { :controller => 'Login', :action => 'index' }) %><br />

<%= link_to_unless(@user, 'ログイン',
  { :controller => 'Login', :action => 'index' }) %><br />

<%= link_to_if(@user.nil?, 'ログイン',
  { :controller => 'Login', :action => 'index' }) do |name|
  link_to('マイページ', { :controller => 'Login', :action => 'info' })
end %>

railbook/app/views/view/partial_basic.html.erb
<div id="info">
  <%= render 'books/book' %>
</div>

railbook/app/views/view/select.html.erb
<%= form_for(@book) do |f| %>
  <%= f.select(:publish, ['技術評論社', '翔泳社', 'マイコミ'],
    { :include_blank => '選択してください' }, { :class => 'pub' }) %><br />
  <%= f.select(:publish,
    { '技術評論社' => 1, '翔泳社' => 2, 'マイコミ' => 3 }) %><br />
  <%= f.select(:publish,
    [['技術評論社', 1], ['翔泳社', 2], ['マイコミ', 3]]) %><br />
  <%= f.select(:publish, ['技術評論社', '翔泳社', 'マイコミ'],
    { :include_blank => '選択してください' }, { :multiple => true }) %>
<% end %>

railbook/app/views/view/simple_format.html.erb
<% article = <<EOL
WINGSニュース特別号

こんにちは。
WINGSプロジェクトの山田です。
今日は、おすすめ書籍の特集をお送りします。
EOL
%>
<%= simple_format(article, { :class => 'article' }) %>

railbook/app/views/view/truncate.html.erb
<% msg = '<strong>Rails</strong>はRubyベースのフレームワークです。Railsに影響を受けたフレームワークには、Catalystやsymfonyなどがあります。' %>

<%= truncate(msg, { :length => 50}) %><br />

<%= truncate(msg, { :length => 50, :separator => '。' }) %><br />

<%= truncate(msg, { :length => 50, :omission => '...後略...' }) %>

railbook/app/views/view/video.html.erb
<%= video_tag('child/sample.mp4', :controls => true, :autoplay => false, :loop => true, :size => '300x150', :poster => 'wings_logo.gif') %>